# Generated by Django 6.0.3 on 2026-04-02 00:33

import eventin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventin', '0003_alter_event_capacity_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='cpf',
            field=models.CharField(max_length=11, unique=True, validators=[eventin.validators.validate_cpf]),
        ),
    ]
