# Generated by Django 6.0.3 on 2026-04-02 00:43

import eventin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventin', '0004_alter_participant_cpf'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='cpf',
            field=models.CharField(max_length=14, unique=True, validators=[eventin.validators.validate_cpf]),
        ),
    ]
