# Generated by Django 6.0.3 on 2026-04-04 22:31

import django.db.models.deletion
import eventin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventin', '0006_alter_event_date_alter_event_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='participant',
            field=models.ManyToManyField(related_name='events', through='eventin.Registration', to='eventin.participant'),
        ),
        migrations.AlterField(
            model_name='event',
            name='capacity',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='participant',
            name='name',
            field=models.CharField(max_length=200, validators=[eventin.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(max_length=16, unique=True, validators=[eventin.validators.validate_phone]),
        ),
        migrations.AlterField(
            model_name='registration',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='eventin.event'),
        ),
        migrations.AlterField(
            model_name='registration',
            name='participant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='eventin.participant'),
        ),
    ]
