# Generated by Django 6.0.3 on 2026-04-07 00:53

import eventin.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventin', '0007_event_participant_alter_event_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[eventin.validators.validate_phone]),
        ),
    ]
